apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: podinfo
  namespace: projectcontour
  annotations:
    fluxcd.io/ignore: "true"
spec:
  virtualhost:
    fqdn: podinfo.example.com
    tls:
      secretName: cert
  includes:
    - name: podinfo
      namespace: demo
