name: test

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate kustomization
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            echo "Run kubeval"
            kustomize build . | kubeval --strict --ignore-missing-schemas
